

title: Rapport de Robotique 

description: >- # this means to ignore newlines until "baseurl:"
  Rapport de robotique pour le groupe : Benjamin BONHOMME, Emma CHATELET, Jules MARGOLLE


url: "https://jules-margolle.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Thème
remote_theme: pmarsceill/just-the-docs

# Paramètres optionnels de "Just the Docs"
just_the_docs:
  navigation_depth: 5
  search_enabled: true
  search_indexing: true

# Plugins
plugins:
  - jekyll-remote-theme

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

